---
title: "Summer Research Project (Other NFL Seasons)"
author: "Sujit Sivadanam"
date: "2024-07-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Necessary Packages

```{r}
library(dplyr)
library(tidyverse)
```

## Obtain Drive Outcomes for each game of each Season

```{r}
all_seasons <- read.csv("./NFL Play by Play 2009-2017 (v4).csv")
drive.by.drive <- NULL #Initialize drive by drive

for(season in unique(all_seasons$Season)){
  play_by_play <- all_seasons %>% filter(Season == season)
  nOrig <- length(unique(play_by_play$GameID))
  print(nOrig)
  
  ## Define Half variable
  play_by_play$Half <- ifelse(play_by_play$qtr %in% c(1,2),
                              1,
                              ifelse(play_by_play$qtr %in% c(3,4),
                                     2,
                                     "OT"))
  
  # where PlayType = "Timeout" or "Two Minute Warning"
  play_by_play <- play_by_play %>% 
    filter(!(PlayType %in% c("Timeout", "Two Minute Warning")))
  
  # where PlayType = "Quarter End" and qtr = 1, 3
  play_by_play <- play_by_play %>%
    filter(!(PlayType == "Quarter End" & qtr %in% c(1,3)))
  
  ## Convert Penalty.Yards into signed version (if posteam is penalized, sign is negative) within each drive
  play_by_play$Penalty.Yards <- ifelse(is.na(play_by_play$Penalty.Yards),
                                     0, play_by_play$Penalty.Yards)

  ## Assign sign to Penalty.Yards
  play_by_play$Penalty.Yards <- ifelse(play_by_play$posteam ==
          play_by_play$PenalizedTeam, -1*play_by_play$Penalty.Yards,
          play_by_play$Penalty.Yards)
  
  ## Variable describing field position change (yrdln[current]-yrdln[next]) within each game, each drive
  play_by_play$pos_net <- c(-1*diff(play_by_play$yrdline100), NA)
play_by_play$pos_net[which(play_by_play$Drive != lead(play_by_play$Drive))] <- NA

  # Locate any mismatches between pos_net
  mismatch <- which(play_by_play$pos_net != play_by_play$Yards.Gained + play_by_play$Penalty.Yards)
  
  ## Create a Kickoff Return.Yards variable
  play_by_play$Return.Yards <- ifelse(play_by_play$PlayType == "Kickoff",
                                    play_by_play$Yards.Gained, NA)

  mismatch_df <- play_by_play[mismatch,] %>% select(Drive, posteam, yrdln, yrdline100, pos_net, Yards.Gained, Return.Yards, Penalty.Yards, Accepted.Penalty, desc, PlayType, qtr) %>% filter(PlayType != "No Play")
  
  ## Create Fumble.Lost variable
  play_by_play$Fumble.Lost <- play_by_play$Fumble
  play_by_play$Fumble.Lost <- ifelse(play_by_play$Fumble == 1 & play_by_play$Drive != lead(play_by_play$Drive), 1, 0)
  
  ## All instances of a fumble recovered for touchdown
  fmb_td_index <- which(play_by_play$Touchdown == 1 & play_by_play$Fumble == 1 & play_by_play$Fumble.Lost == 0)
  
  ## All instances of a touchdown
  td_index <- which(play_by_play$Touchdown == 1)
  
  ## Home.Team.Sc and Away.Team.Sc
  play_by_play$Home.Team.Sc <- ifelse(play_by_play$posteam == play_by_play$HomeTeam, play_by_play$PosTeamScore, play_by_play$DefTeamScore)
  
  play_by_play$Away.Team.Sc <- ifelse(play_by_play$posteam == play_by_play$AwayTeam, play_by_play$PosTeamScore, play_by_play$DefTeamScore)
  
  ## Home.Team.Points and Away.Team.Points
  play_by_play$Home.Team.Points <- c(diff(play_by_play$Home.Team.Sc), NA)
  play_by_play$Away.Team.Points <- c(diff(play_by_play$Away.Team.Sc), NA)
  
  # Makes sure that differences don't include different games
  play_by_play$Home.Team.Points[which(play_by_play$GameID != lead(play_by_play$GameID))] <- NA
  play_by_play$Away.Team.Points[which(play_by_play$GameID != lead(play_by_play$GameID))] <- NA
  
  ## Assign 3 points to home and away teams where their score is NA & field goal made
  home_away_NAs <- which(is.na(play_by_play$Home.Team.Points) & play_by_play$FieldGoalResult == "Good")
  
  play_by_play$Home.Team.Points[home_away_NAs] <- ifelse(play_by_play$posteam[home_away_NAs] == play_by_play$HomeTeam[home_away_NAs], 3, 0)
  
  play_by_play$Away.Team.Points[home_away_NAs] <- ifelse(play_by_play$posteam[home_away_NAs] == play_by_play$AwayTeam[home_away_NAs], 3, 0)
  
  ## Assign 6 points to home and away teams where their score is NA & TD scored
  TD_home_away_NAs  <- which(is.na(play_by_play$Home.Team.Points) &
                               play_by_play$Touchdown == 1)
  
  play_by_play$Home.Team.Points[TD_home_away_NAs] <- ifelse(play_by_play$posteam[TD_home_away_NAs] == play_by_play$HomeTeam[TD_home_away_NAs], 6, 0)
  
  play_by_play$Away.Team.Points[TD_home_away_NAs] <- ifelse(play_by_play$posteam[TD_home_away_NAs] == play_by_play$AwayTeam[TD_home_away_NAs], 6, 0)
  # We're yet to know if these TDs are offensive or defensive
  
  ## Assign 2 points to home and away teams where their score is NA & safety scored
  sfty_NAs <- which(is.na(play_by_play$Home.Team.Points) & play_by_play$Safety == 1)
  
  play_by_play$Home.Team.Points[sfty_NAs] <- ifelse(
    play_by_play$DefensiveTeam[sfty_NAs] == play_by_play$HomeTeam[sfty_NAs], 2, 0)
  
  play_by_play$Away.Team.Points[sfty_NAs] <- ifelse(
    play_by_play$DefensiveTeam[sfty_NAs] == play_by_play$AwayTeam[sfty_NAs], 2, 0)
  
  ## Remove the half where TD and Safety == 1
  badIndex <- which(play_by_play$Touchdown == 1 & play_by_play$Safety == 1)
  play_by_play <- play_by_play %>% filter(!(play_by_play$GameID %in% play_by_play$GameID[badIndex]))
  
  ## Check for "clean" punts that are NOT of "Punt" playtype
  clean.punt <- which(!is.na(play_by_play$PuntResult) & play_by_play$PlayType != "Punt")

  ## Sanity check to see if drive no. of punt play is different from drive no. of next play
  bad.punt.indx <- which(play_by_play$PlayType == "Punt" & play_by_play$Drive == lead(play_by_play$Drive) & !str_detect(tolower(play_by_play$desc), "fake punt"))
  
  ## Removes instances of the above ---Big Removal of Games
  badGameIDs <- play_by_play$GameID[bad.punt.indx]
  play_by_play <- play_by_play %>% filter(!(GameID %in% badGameIDs))
  print(length(unique(play_by_play$GameID)))
  
  ## Punt not followed by 2 consecutive plays of same drive
  punt_indx2 <- which(!is.na(play_by_play$PuntResult) & !(play_by_play$Drive == lead(play_by_play$Drive) & play_by_play$Drive == lead(play_by_play$Drive, 2)))
  
  # Switches
  play_by_play[punt_indx2, c("posteam", "DefensiveTeam", "PosTeamScore", "DefTeamScore")] <- play_by_play[punt_indx2, c("DefensiveTeam", "posteam", "DefTeamScore", "PosTeamScore")]
  
  ## Change drive number into the next drive number
  play_by_play$Drive[punt_indx2] <- play_by_play$Drive[punt_indx2]+1
  
  ## Create Pos.Team variable
  play_by_play$Pos.Team.Points <- ifelse(play_by_play$posteam == play_by_play$HomeTeam,
                                         ifelse(play_by_play$Home.Team.Points >= play_by_play$Away.Team.Points,
                                                play_by_play$Home.Team.Points,
                                                -1*play_by_play$Away.Team.Points),
                                         ifelse(play_by_play$Away.Team.Points >= play_by_play$Home.Team.Points,
                                                play_by_play$Away.Team.Points,
                                                -1*play_by_play$Home.Team.Points))
  
  ## Extracting last play for each drive of every Game
  last.play.drive <- play_by_play %>% group_by(GameID, Drive) %>% summarize(nxt.drive.first.play = head(PlayType,1), nxt.drive.punt.result = head(PuntResult,1), nxt.drive.qtr = head(qtr,1), points = tail(Pos.Team.Points,1), qtr = tail(qtr,1), down = tail(down,1), PlayType = tail(PlayType,1), desc = tail(desc,1), Fumble.Lost = tail(Fumble.Lost,1), InterceptionThrown = tail(InterceptionThrown,1), FieldGoalResult = tail(FieldGoalResult,1), ChalReplayResult = tail(ChalReplayResult,1), TwoPointConv = tail(TwoPointConv,1), Onsidekick = tail(Onsidekick,1), posteam = head(posteam,1)) %>% ungroup() %>% mutate(nxt.drive.first.play = lead(nxt.drive.first.play), nxt.drive.punt.result = lead(nxt.drive.punt.result), nxt.drive.qtr = lead(nxt.drive.qtr), .by="GameID")
  
  ## Last play was 6 points without extra point following it
  no.xtra.pts <- last.play.drive %>% filter(points == 6)
  
  bad.drive.end <- play_by_play %>% filter(GameID %in% no.xtra.pts$GameID) %>% group_by(GameID) %>% summarize(last.drive = tail(Drive,1)) %>% left_join(no.xtra.pts) %>% 
    filter(last.drive != Drive) %>% .[["GameID"]]
  
  ## Removing bad.drive.end (GameID) games from play_by_play ---Big Removal of Games
  play_by_play <- play_by_play %>% filter(!(GameID %in% bad.drive.end))
  print(length(unique(play_by_play$GameID)))
  
  ## Initializing drive outcome
  last.play.drive$Drive.Outcome <- NA
  
  ## When last.play.points = 3 (field goal)
  last.play.drive$Drive.Outcome[last.play.drive$points == 3] <- "Made Field Goal"
  
  ## When last.play.points = -2 (safety)
  last.play.drive$Drive.Outcome[last.play.drive$points == -2] <- "Safety"
  
  ## When last.play.points = 1, 2, or 6 (off TD)
  last.play.drive$Drive.Outcome[last.play.drive$points %in% c(1,2,6) | last.play.drive$PlayType == "Extra Point" | !is.na(last.play.drive$TwoPointConv)] <- "Offensive Touchdown"
  
  ## When last.play.points == -6 (def TD)
  last.play.drive$Drive.Outcome[last.play.drive$points == -6] <- "Defensive Touchdown"
  
  ## Drive ends with half end
  last.play.drive$Drive.Outcome[(last.play.drive$PlayType %in% c("Half End", "End of Game")) | (last.play.drive$PlayType == "Quarter End" & last.play.drive$qtr %in% c(2,4,5))] <- "End of Half"
  
  ## Drive ends with interception
  last.play.drive$Drive.Outcome[last.play.drive$points == 0 & last.play.drive$InterceptionThrown == 1] <- "Interception"
  
  ## Drive ends with fumble
  #Change Fumble indicator to 0 due to reversal
  fmb_aft <- str_detect(str_remove_all(tolower(last.play.drive$desc), ".*reverse"), "fumble")
  last.play.drive$Fumble.Lost[!fmb_aft] <- 0
  
  last.play.drive$Drive.Outcome[last.play.drive$Fumble.Lost == 1] <- "Fumble"
  
  ## Drive ends with missed or blocked field goal
  last.play.drive$Drive.Outcome[last.play.drive$FieldGoalResult %in% c("No Good", "Blocked")] <- "Missed Field Goal"
  
  ## Drive ends with punt
  last.play.drive$Drive.Outcome[which(!is.na(last.play.drive$nxt.drive.punt.result))] <- "Punt"
  
  ## Quarter transitions from 2 to 3 or from 4 to 5 (OT)
  last.play.drive$Drive.Outcome[which(((last.play.drive$qtr == 2 & last.play.drive$nxt.drive.qtr == 3) | (last.play.drive$qtr == 4 & last.play.drive$nxt.drive.qtr == 5)) & is.na(last.play.drive$Drive.Outcome))] <- "End of Half"
  
  ## Remove badly recorded games ---Big Removal of Games
  bad.record.ind <- which(!is.na(last.play.drive$nxt.drive.first.play) & last.play.drive$down != 4 & is.na(last.play.drive$Drive.Outcome))
  bad.record <- last.play.drive$GameID[bad.record.ind]
  
  play_by_play <- play_by_play %>% filter(!(GameID %in% bad.record))
  print(length(unique(play_by_play$GameID)))
  last.play.drive <- last.play.drive %>% filter(!(GameID %in% bad.record))
  
  ## Drive ends with time running out
  last.play.drive$Drive.Outcome[which(((is.na(last.play.drive$nxt.drive.first.play) & last.play.drive$down != 4) | (last.play.drive$down == 4 & last.play.drive$PlayType == "Punt")) & is.na(last.play.drive$Drive.Outcome))] <- "End of Half"
  
  ## Drive involves onside kick recovery
  last.play.drive$Drive.Outcome[last.play.drive$Onsidekick == 1 & last.play.drive$posteam != lead(last.play.drive$posteam) & str_detect(last.play.drive$desc, "RECOVER")] <- "Onside Kick Recovery"
  
  ## Drive ends with turnover on downs
  last.play.drive$Drive.Outcome[is.na(last.play.drive$Drive.Outcome)] <- "Turnover on Downs"
  
  ## Merge last.play.drive with play_by_play
  play_by_play <- play_by_play %>% left_join(last.play.drive %>% select(GameID, Drive, Drive.Outcome))
  
  # nNew <- length(unique(play_by_play$GameID))
  # print(season)
  # print(1 - (nNew/nOrig))
  # print(table(last.play.drive$Drive.Outcome))
  
  ## Calculate Numerical Statistics
  drive.by.drive <- rbind(drive.by.drive, play_by_play %>% group_by(Season, GameID, Drive) %>% summarize(n.sacks = sum(Sack),
                                                                                                         n.completions = sum(PassOutcome == "Complete", na.rm=T),
                                                                                                         n.incompletions = sum(PassOutcome == "Incomplete", na.rm=T),
                                                                                                         n.stuffed.runs = sum(RushAttempt == 1 & pos_net <= 0, na.rm=T),
                                                                                                         n.positive.runs = sum(RushAttempt == 1 & pos_net > 0, na.rm=T),
                                                                                                         n.negative.plays = sum(pos_net < 0 & PlayType != "Kickoff", na.rm=T),
                                                                                                         n.fumbles = sum(Fumble == 1, na.rm=T),
                                                                                                         first.downs.gained = sum(FirstDown == 1 & pos_net > 0, na.rm=T),
                                                                                                         third.downs.converted = sum(FirstDown == 1 & pos_net > 0 & lag(down) == 3, na.rm=T),
                                                                                                         takeaway.nonscore = ifelse((InterceptionThrown[1] == 1 | Fumble.Lost[1] == 1 | (Onsidekick[1] == 1 & posteam[1] != lead(posteam[1]) & str_detect(desc[1], "RECOVER"))) & Drive.Outcome[1] != "Defensive Touchdown",1,0),
                                                                                                         turnover.nonscore = ifelse(takeaway.nonscore == 1 | Drive.Outcome %in% c("Missed Field Goal", "Turnover on Downs"),1,0),
                                                                                                         punt.safety = ifelse(Drive.Outcome %in% c("Punt", "Safety"),1,0),
                                                                                                         pts.scored = sum(Pos.Team.Points, na.rm=T),
                                                                                                         ST.return.yards.net = ifelse((head(PlayType,1) %in% c("Kickoff", "Punt")) | !str_detect(tolower(desc),"touchback") | !str_detect(tolower(desc),"fair catch") | !str_detect(tolower(desc),"penalty"), tail(as.numeric(unlist(str_extract_all(desc, "[+-]?\\d+"))),1), 0),
                                                                                                         off.ST.start.pos = ifelse(head(PlayType,1) %in% c("Kickoff", "Punt"), head(yrdline100,2)[2], head(yrdline100,1)),
                                                                                                         off.ST.yards.gained = off.ST.start.pos-ifelse(head(Drive.Outcome,1) != "Offensive Touchdown", ifelse(head(Drive.Outcome,1) == "Punt", off.ST.start.pos-tail(as.numeric(unlist(str_extract_all(desc, "[+-]?\\d+"))),1), tail(yrdline100,1)), 0)+ST.return.yards.net))
}
```

## Saving drive.by.drive in a CSV file

```{r}
write_csv(drive.by.drive, "./Drive_by_Drive_Data.csv")
```
